### ISSUE TITLE
Results directory tree is confused.

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#40]
<my config>
project_root:           .../w3Genomon
sample_name:            MCF-7_yshira_100
analysis_date:          today
file_name:                  sequence{pair_id}.fastq
pair_id:
                            - 1
                            - 2

<results>
.../w3Genomon/results/MCF-7_yshira_100/out/20150707/star/MCF-7_yshira_100/
sequence1_Chimeric.out.sam
：
：

Header "sequence1_" is not clearly understandable.
I think the following one is better. 
...out/20150707/star/MCF-7_yshira_100_Chimeric.out.sam

**Comment by eigoshimizu** [comment]
この仕様は、前のミーティングで話し合って決まったものです。
今度のミーティングで、もう一度議論したいと思います。

**Comment by eigoshimizu** [comment]
#66 でも議論されているので、とりあえず、 close します。
