### ISSUE TITLE
Exception AttributeError: "RunTask instance has no attribute 'drmaa'

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#46]
/usr/local/package/python2.7/current/bin/python $3 /home/w3varann/tools/Genomon/genomon.py \
           --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg \
           --job_file $1 \
           --param_file $2 \
           --jobs 300 \
           --verbose 10 \
           --drmaa
+ /usr/local/package/python2.7/current/bin/python /home/w3varann/tools/Genomon/genomon.py --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg --job_file config/prj_8572_star_job.yaml --param_file config/prj_8572_param.yaml --jobs 300 --verbose 10 --drmaa

Generated by /home/w3varann/tools/Genomon/genomon.py
    Input config file = /home/w3varann/tools/Genomon/samples/genomon.cfg
    Input job file    = config/prj_8572_star_job.yaml
    RunTask: run_mode=DRMAA
    main: Unexpected error
    <type 'exceptions.ImportError'>: genomon.py:368
Exception AttributeError: "RunTask instance has no attribute 'drmaa'" in <bound method RunTask.__del__ of <helpers.runtask.RunTask instance at 0x2abf80eb1a70>> ignored

**Comment by eigoshimizu** [comment]
/home/w3varann に drmaa がインストールされていませんでした。
初歩的なミスですいません。
drmaa のライブラリを /home/eigos からコピーしました。

**Comment by eigoshimizu** [comment]
動作すると思います。
クローズしますが、治っていないようであれば、再度オープンしてください。
よろしくお願いいたします。
