### ISSUE TITLE
param.yamlのbwa_memはadditional_paramsにしてほしい。

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/Genomon#51]
①param.yamlのbwa_memはadditional_paramsの方が良いと思います。
②samples/genomon.cfgのようにすべてツールが1つのparam.yamlファイルにまとまっていたほうが良いと思います。
③additional_paramsと'additional_params'（シングルクォーテーションで囲まれているものがあるので)、囲まないもので統一しましょう。

**Comment by eigoshimizu** [comment]
①param.yamlのbwa_memはadditional_params
現在テスト中です。

②samples/genomon.cfgのようにすべてツールが1つのparam.yamlファイルにする
joy.yaml といっしょに対応していきます。

③additional_paramsと'additional_params'（シングルクォーテーションで囲まれているものがあるので)、囲まないもので統一
訂正します。

**Comment by eigoshimizu** [comment]
対応しました。
Close します。
