### ISSUE TITLE
EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#58]
32GBでqloginして実行
run.shのgenomon.py 　のプロセス関係のオプションは以下。
           --jobs 200 \
           --verbose 1 \
           --drmaa \
           --use_threads

Read from SAindex: genomeSAindexNbases=14  nSAi=357913940
Genome file size: 3220476720 bytes; state: good=1 eof=0 fail=0 bad=0
SA file size: 24496209986 bytes; state: good=1 eof=0 fail=0 bad=0
nGenome=3220476720;  nSAbyte=24496209986
GstrandBit=32   SA number of indices=5938475148

EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc
Possible cause 1: not enough RAM. Check if you have enough RAM 31282560594 bytes
Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 31282560594

Aug 05 18:07:48 ...... FATAL ERROR, exiting
＝＝＝
必要とされるmemoryはエラーとなった全件同じです
ulimit -v 31282560594　　　<= 29.13 GB
でstar　のqsub 時のreq_mem 32GBを超えてはいません
100件以上は正常終了するものの1000件以上が同じエラーになるといった状況です。

正常終了する場合はEXITINGメッセージのところに代わりに以下のログが続きます
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 3220476720 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 3220476720 bytes
SA file size: 24496209986 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 24496209986 bytes
Loading SAindex ... done: 1565873616 bytes

このファイルのLoadに必要となるメモリは
Genome file size:+ SA file size:+ SAindex で
3220476720 + 24496209986 + 1565873616 = 29282560322 (27.27 GB)です
31282560594 - 29282560322 = 2000000272

約1200件を一気に実行しようとして成功するのが 150件～200件
その他はすべてallocate 失敗
並行実行の指定方法または上限に問題ありと言うことだと思います

run.shの標準出力には以下のエラーが出ていました
star: Unexpected error: <type 'exceptions.Exception'>.
    <type 'exceptions.Exception'>: star_pipeline.py:298
 
＝＝＝＝＝＝＝＝＝＝＝＝
TARGETデータの解析時も1件出ていましたが
再実行したらうまくいったので　するーしていました
TARGETの時は
 --jobs 150 　のみで　--drmaa 　--use_threads　指定なしで実行
Loadに必要となるメモリは28753700891　で
やはり
30753701163　-　28753700891 = 2000000272
で同じなので、STARで一定の使用分2000000272を足した値を
ulimitで指定するようにとエラーをだしているようです

尚、
実行時のプロセス数は　--jobs 150 のみの時は　150+3　でしたが
--drmaa --use_threads を使うと　4 で抑制されています

**Comment by eigoshimizu** [comment]
詳細な報告ありがとうございます。
下記に田中さんからのメールを添付いたします。
-----
ulimitで指定するように、
というFATAL ERRORが出ている不具合ですが、
GEのメモリ管理不具合が原因とほぼ見当がつきました。
STARジョブがランしたホストにリクエストしたメモリ量より多く使用しているユーザーがいるのだと思われます
たぶんmem_reqでGをつけていないジョブが入っているホストに後からSTARジョブが入って必要量を確保できないのです。

パイプライン側の問題ではありません。
-----

:star_pipeline.py:298 
は、exception が起こった場所です。 star_pipeline.pyの中の、star のジョブを投入するところです。
投入したジョブが失敗したので、exceptionになったものと考えられます。
ジョブが失敗したら、パイプラインを止めるようにしなければなりませんが、drmaaの部分にバグがあり、昨日の14:16に修正を入れました。

--drmaa --use_threads 使用で、実行時のプロセス数が、４になるのは良いですね。

**Comment by roko-t** [comment]
以下、スパコンサポートに問い合わせ中。
==============================
現在Shirokane3で1200件弱のTCGAデータをSTARというツールを使って
RNAseq解析を行っているのですが
サンプル毎にジョブを投入して200件位は正常終了しているのですが
その他の1000件でエラーになってしまいました
すべて以下のようなエラーが出ていてサンプル依存ではありませんし、
再度実行すれば正常終了します

EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc
Possible cause 1: not enough RAM. Check if you have enough RAM 31282560594 bytes  
Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 31282560594
Aug 04 21:22:04 ...... FATAL ERROR, exiting

31282560594　(29.13GB)　必要と出ていますが
ジョブは32GB をリクエストして投入しています
STARはプログラムの最初に必要量を計算して確保できないとexit_status 108 ですぐに終了します
今朝0時以降開始のexit_status 108となったジョブをqreport からリストアップしましたので添付します

ジョブ960件が以下の５つの同じホストに投入されてはすぐに異常終了するという状況が起きています
sc046i
sc045i
sc078i
sc019i
sc088i
特にsc078iへの投入538回、sc045iへの投入392回　です

自分が異常終了して空いたホストにまた投入されては異常終了しているのだと思います

先に入っているユーザのジョブがリクエストした以上のメモリを使用していて
メモリを確保できない状態になっているのではないでしょうか？

**Comment by roko-t** [comment]
--jobs 500 でSTAR　501件submitされ、メモリアロケートエラーなく、全jobランできています
制限をつける必要はなさそうです
次回--jobsを設定せずに実行してみます
