### ISSUE TITLE
sampleプロジェクト実行中に 'pipeline.stage_7' でエラー発生

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/Genomon#61]
sampleプロジェクト実行中に `Task enters queue = 'helpers.wgs_pipeline.stage_7` でエラーが発生し終了しました。
以下はエラーが発生した `bam_stats_calc_xxx` のエラーログです。

<pre>
+ /home/w3varann/tools/PCAP-core-dev.20150511/bin/bam_stats.pl --threads 4 -i ./results/small_SRR330441/out/bam/small_SRR330441_markdup.bam -o ./results/small_SRR330441/out/summary/small_SRR330441.txt.1
IPC::System::Simple required for Fatalised/autodying system() at /home/w3varann/tools/PCAP-core-dev.20150511/bin/bam_stats.pl line 24
BEGIN failed--compilation aborted at /home/w3varann/tools/PCAP-core-dev.20150511/bin/bam_stats.pl line 24.
+ check_error 2
+ '[' 2 -ne 0 ']'
+ echo 'FATAL ERROR: pipeline script'
+ echo 'ERROR CODE: 2'
+ exit 2
</pre>

**Comment by eigoshimizu** [comment]
bam_stats.pl が、perl のモジュール IPC::System::Simple がひつようになります。

PERL5LIB=/home/w3varann/.local/lib/perl/lib

を shell script に入れる必要があります。

**Comment by eigoshimizu** [comment]
変更を push しました。

**Comment by eigoshimizu** [comment]
Close しますが、再現する場合は、再度open してください。
