### ISSUE TITLE
STAR:未完了サンプルを実行してくれない

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#65]
STARで1198件中1088件完了（*final.outあり、かつ*Log.outに"ALL DONE"出力あり）
残件を実行してくれない
ログは以下で終了している
/usr/local/package/python2.7/current/bin/python $3 /home/w3varann/tools/Genomon/genomon.py \
           --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg \
           --job_file $1 \
           --param_file $2 \
           --jobs 500 \
           --verbose 1 \
           --drmaa \
           --use_threads
+ /usr/local/package/python2.7/current/bin/python /home/w3varann/tools/Genomon/genomon.py --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg --job_file config/CD274_RNA_150731_job_20150805_star.yaml --param_file config/CD274_RNA_150731_param_star_limitBAMsortRAM_max.yaml --jobs 500 --verbose 1 --drmaa --use_threads

Generated by /home/w3varann/tools/Genomon/genomon.py
    Input config file = /home/w3varann/tools/Genomon/samples/genomon.cfg
    Input job file    = config/CD274_RNA_150731_job_20150805_star.yaml
    RunTask: run_mode=DRMAA

    ________________________________________
    Tasks which will be run:

    Task enters queue = 'helpers.star_pipeline.last_function'
    Genomon pipline has finished successflly!
    Completed Task = 'helpers.star_pipeline.last_function'

**Comment by roko-t** [comment]
未完了サンプルの出力先のファイルを全削除して再実行で、残件開始。

**Comment by eigoshimizu** [comment]
STAR の実行が正常終了しているかのチェックで見る出力ファイルを
XXX_Chimeric.out.junction
から
XXX_Log.final.out
に変更します。
よろしくお願いいたします。

**Comment by eigoshimizu** [comment]
develop branch に変更を入れました。
