### ISSUE TITLE
STAR:option --outSAMunmapped（unmapped readsを含めるか否か）

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#69]
--outSAMunmapped
現在指定していないのでdefault Noneでunmapped reads が
sequence1_Aligned.sortedByCoord.out.bam　に含まれていない
Genomon　pipelineの仕様としては含めるべきではないか？

====
default: None
string: output of unmapped reads in the SAM format
None
no output
Within
output unmapped reads within the main SAM le (i.e.
Aligned.out.sam)

**Comment by eigoshimizu** [comment]
STAR をどのように動作させるかの問題になります。
白石さん、千葉さんの助言が必要です。
よろしくお願いいたします。

**Comment by friend1ws** [comment]
これは含めたいです。bamからfastqが復元出来るのがベターです。

**Comment by eigoshimizu** [comment]
了解です。
デフォルトの parameter をして設定します。
よろしくお願いいたします。

**Comment by eigoshimizu** [comment]
develop branch の resource/default_param.yaml にデフォルトの star のパラメータを設定しました。

```
--outSAMunmapped Within
--outSAMunmapped Within
```
