### ISSUE TITLE
STAR:正常完了していたbamからbai作成で1198件中3件error

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#70]
1.the alignment is not sorted: reads without coordinates prior to reads with coordinates.　1件
2.Segmentation fault 2件

STARをパイプラインを通さず直接再実行したら
3件ともbam のファイルサイズに20バイト前後の差が出たが正常完了し、
以下のファイルは基本的に一致していた
(1) Chimeric.out.junction,SJ.out.tab  　identical
(2) Chimeric.out.sam パスが記載されている@PG、 @CO行を除いて　identical
(3) Log.final.out、が時刻,処理時間を除いてidentical

**Comment by eigoshimizu** [comment]
田中さん、

Segmentation fault なので、メモリーが足りなくて落ちている感じですが、どうでしょうか？

エラーになっている３件の star と star_fusion のログの場所を教えていただけますか？
よろしくお願いいたします。

**Comment by roko-t** [comment]
/home/ogawalab/workspace/h_tanaka/150730_TCGA_CD274/results/CD274_RNA_150731/out/err_20150805/star
にerrorになったデータはおいてあります
ログは
/home/ogawalab/workspace/h_tanaka/150730_TCGA_CD274/results/CD274_RNA_150731/log/0806
の
star_20150806_1214_400545.sh.e779467
star_20150806_1214_812244.sh.e779525
star_20150806_0555_678162.sh.e772891

3件ともSTARのログLog.outもジョブのstatusも正常終了していたので、原因不明。
また、
3サンプルともパイプラインでも実行してみました。今度はbaiを作成することができました
再実行分は
/home/ogawalab/workspace/h_tanaka/150730_TCGA_CD274/results/CD274_RNA_150731/out/retry_20150805
に置いてあります
追跡もここまでかと。。。

**Comment by eigoshimizu** [comment]
ありがとうございます。
ログを見てみましたが、わかりませんね。
これも他のジョブのためにリソースが圧迫されて、Segmentaton fault とかになった可能性がありますね。

**Comment by eigoshimizu** [comment]
この件は一旦 close して、もう一度再現する場合は、新たに issue を open してください。
よろしくお願いいたします。
