### ISSUE TITLE
データのクリーンアップ(中間ファイルの削除など)

### ISSUE THREAD

**Issue by eigoshimizu** [Genomon-Project/Genomon#8]
解析終了後に中間ファイルの削除を行う必要がある。

**Comment by friend1ws** [comment]
ruffusのページを見ていると、いくつか参考になりそうな方法が書いてありますね。
http://www.ruffus.org.uk/faq.html#q-keeping-large-intermediate-files
http://www.ruffus.org.uk/tutorials/new_tutorial/dependencies.html#esoteric-option-minimal-reruns

**Comment by eigoshimizu** [comment]
必要なファイルは削除します。
ruffus であるかをみているファイルは、サイズを 0 にしています。
テスト完了。push しました。
closeします。
